import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../../src/components/layout/header";
import Footer from "../../src/components/layout/footer";
import {Bricolage_Grotesque } from 'next/font/google'

const grotesque = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ['200', '300', '400', '500', '600', '700', '800'], // Add weights you need
  variable: '--font-grotesque',
  display: 'swap', 
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={grotesque.className}>
      <body>
        <Header />
        <main>
        {children}
        </main>
        <Footer />

      </body>
    </html>
  );
}
